version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone/example"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone_platform_interface"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone_android"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone_ios"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone_linux"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone_macos"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone_web"
    schedule:
      interval: "daily"
  - package-ecosystem: "pub"
    directory: "/system_timezone_windows"
    schedule:
      interval: "daily"