name: system_timezone_platform_interface
description: A common platform interface for the system_timezone plugin.
version: 0.1.0+1
publish_to: none
repository: https://github.com/HosamHasanRamadan/system_timezone

environment:
  sdk: ^3.4.0

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
