name: system_timezone_windows
description: Windows implementation of the system_timezone plugin
version: 0.1.0+1
repository: https://github.com/HosamHasanRamadan/system_timezone

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: system_timezone
    platforms:
      windows:
        dartPluginClass: SystemTimezoneWindows
        ffiPlugin: true

dependencies:
  ffi: ^2.1.2
  flutter:
    sdk: flutter
  system_timezone_platform_interface: ^0.1.1+2

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
