name: system_timezone_macos
description: MacOS implementation of the system_timezone plugin
version: 0.2.0+1
repository: https://github.com/HosamHasanRamadan/system_timezone

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: system_timezone
    platforms:
      macos:
        dartPluginClass: SystemTimezoneMacOS

dependencies:
  flutter:
    sdk: flutter
  objective_c: ^1.1.0
  system_timezone_platform_interface: ^0.2.0+1

dev_dependencies:
  ffigen: ^13.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
