name: system_timezone_macos
description: MacOS implementation of the system_timezone plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: system_timezone
    platforms:
      macos:
        dartPluginClass: SystemTimezoneMacOS
        ffiPlugin: true

dependencies:
  flutter:
    sdk: flutter
  objective_c: ^1.0.1
  system_timezone_platform_interface:
    path: ../system_timezone_platform_interface

dev_dependencies:
  ffigen: ^12.0.0
  flutter_test:
    sdk: flutter
  very_good_analysis: ^6.0.0
