name: system_timezone_ios
description: iOS implementation of the system_timezone plugin
version: 0.1.0+1
repository: https://github.com/HosamHasanRamadan/system_timezone

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

flutter:
  plugin:
    implements: system_timezone
    platforms:
      ios:
        dartPluginClass: SystemTimezoneIOS

dependencies:
  flutter:
    sdk: flutter
  objective_c: ^1.1.0
  system_timezone_platform_interface: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
  ffigen: ^13.0.0
