name: system_timezone_ios
description: iOS implementation of the system_timezone plugin
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: system_timezone
    platforms:
      ios:
        dartPluginClass: SystemTimezoneIOS
        ffiPlugin: true

dependencies:
  flutter:
    sdk: flutter
  objective_c: ^1.0.1
  system_timezone_platform_interface: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
  ffigen: ^12.0.0
