name: system_timezone_android
description: Android implementation of the system_timezone plugin
version: 0.1.0+1
repository: https://github.com/HosamHasanRamadan/system_timezone

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: system_timezone
    platforms:
      android:
        dartPluginClass: SystemTimezoneAndroid
        ffiPlugin: true

dependencies:
  flutter:
    sdk: flutter
  jni: ^0.10.1
  system_timezone_platform_interface: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  jnigen: ^0.10.0
  plugin_platform_interface: ^2.1.8
  very_good_analysis: ^5.1.0
