name: system_timezone_web

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  pull_request:
    paths:
      - ".github/workflows/system_timezone_web.yaml"
      - "system_timezone_web/**"
  push:
    branches:
      - main
    paths:
      - ".github/workflows/system_timezone_web.yaml"
      - "system_timezone_web/**"

jobs:
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.22.0
      working_directory: system_timezone_web

