name: system_timezone_web
description: Web implementation of the system_timezone plugin
version: 0.1.0+1
repository: https://github.com/HosamHasanRamadan/system_timezone

environment:
  sdk: ^3.4.0

flutter:
  plugin:
    implements: system_timezone
    platforms:
      web:
        pluginClass: SystemTimezoneWeb
        fileName: system_timezone_web.dart

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  js: ^0.7.1
  system_timezone_platform_interface: ^0.1.0+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.1.0
